# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B_IgAajQzIOi84_gCE9rPo8Rxa1UupwB

1. CSV Reading and Parsing
"""

import numpy as np
from scipy import stats
import pandas as pd

data = pd.read_csv('/content/sample_data/california_housing_test.csv')
print(data.head)

def load_csv(file_path):
    try:
        df = pd.read_csv(file_path)
        return df
    except Exception as e:
        raise RuntimeError(f"Error loading CSV file: {e}")

# Example usage
file_path = '/content/sample_data/california_housing_test.csv'
df = load_csv(file_path)
print(df.head())

"""2. Perform basic statistical analysis on the data, such as calculating the mean, median, mode,
standard deviation, and correlation coefficient
"""

data.info()

data['population'].mean()

data['population'].median()

data['population'].mode()

data.std()

data.corr()

"""Generate plots of the data, such as histograms, scatter plots, and line plots etc."""

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(10, 6))
sns.histplot(data['population'], bins=30, kde=False)
plt.title('Histogram of column_name')
plt.xlabel('Value')
plt.ylabel('Frequency')
plt.show()

plt.figure(figsize=(10, 6))
sns.scatterplot(x='population', y='latitude', data=df)
plt.title('Scatter Plot of A vs B')
plt.xlabel('population')
plt.ylabel('latitude')
plt.show()

plt.figure(figsize=(12, 10))
sns.pairplot(data)
plt.title('Pair Plot of DataFrame')
plt.show()

correlation_matrix = data.corr()

plt.figure(figsize=(12, 10))
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt='.2f')
plt.title('Correlation Heatmap')
plt.show()

plt.figure(figsize=(10, 6))
sns.lineplot(x='population', y='longitude', data=data, marker='o')
plt.title('Line Plot of A vs C')
plt.xlabel('population')
plt.ylabel('longitude')
plt.show()

"""**Answer questions about the data in a comprehensive and informative way?**
To thoroughly understand and analyze our data, we can follow a structured approach that involves several steps. Here’s a comprehensive guide to getting to know our data:
"""

print("Shape of the DataFrame:", data.shape)

print("\nData Types:\n", data.dtypes)

print("\nColumn Names:\n", data.columns)

print("\nSummary Statistics:\n", data.describe())

print("\nMissing Values:\n", data.isnull().sum())